# Generated by Django 5.1.3 on 2024-11-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizzaHome", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitems",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
